AZURE_TRANSLATOR_KEY = "DmKSSxwTL2nxD1T1HUvoCzor66FhmoVWWwBhb8Xys2l7ZIPKcuS0JQQJ99BKAC5T7U2XJ3w3AAAbACOGU5di"
AZURE_TRANSLATOR_REGION = "francecentral"

AZURE_SPEECH_KEY = "7syuAIsC2Umqwslt9oYns2ESaJb84D7FXzVCt7gcHEqPWfksE0pDJQQJ99BJAC5T7U2XJ3w3AAAYACOGVhGZ"
AZURE_SPEECH_REGION = "francecentral"
